### ISSUE TITLE
Article Header

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#100]
**Issue Type:** New Feature

## Description
A component containing the article's main title, sub-title and related elements.

## Links

Desktop: https://app.zeplin.io/project/59b4e63a7a92547269089328/screen/59b4e670b310f781615188dd
Mobile: https://app.zeplin.io/project/59b4e63a7a92547269089328/screen/5a2cfeac3b17ddf1b898fb95 

## Implementation Details

The `<ArticleHeader />` component, rendered as a `header` element, to group the following subcomponents together:

* `<ArticleKicker />` component, rendered as a `span` element
* `<ArticleTitle />` component, rendered as an `h1` element
* `<ArticleSubTitle />` component, rendered as a `p` element

Despite being two separate elements, <ArticleHeader />` should allow to render `<ArticleKicker/>` and `<ArticleTitle/>` both as two separate blocks, and inline side by side using an `hasInilineKicker` prop that will be passed to both sub-components as an `isIniline` prop:
```
// as two blocks:
ArticleKicker#### 
ArticleTitle##### ######## #######
##### #### #### #### ####

// side by side
ArticleKicker#### ArticleTitle##### ######## #######
##### #### #### #### ####
```

The  `<ArticleKicker />` component should take a `suffix` prop, used to flexibly decide how (and if) an inline kicker is separated from the title.

**Questions:** Should the component allow for a different mobile title, kicker and subtitle? We use this in teasers, but is it also used in the article page itself?

## Testing Requirements

  * snapshot testing

## Work Time Estimation

[n] hours

**Comment by TxHawks** [comment]
@adibi83 Should the component allow for a different mobile title, kicker and subtitle? We use this in teasers, but is it also used in the article page itself?

**Comment by adibi83** [comment]
Yes, the mobile exclusive, title & subtitle are relevant for the article page too
