### ISSUE TITLE
Workflow for creating new packages

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#11]
The root `README.md` should include documentation on the steps required to create a new package. 

Should add a script that does that to the root `package.json`

**Comment by exogen** [comment]
In order to avoid any globally-installed packages (like Yeoman, or installing `htz-scripts` globally), I'm a fan of deferring inital `package.json` creation to a built-in command like `npm/yarn init -y`. We could recommend:

```sh
yarn init -y && yarn add -D htz-react-base && ./node_modules/.bin/htz-scripts init`

Or if you're in an existing package, maybe you could create a sibling one like:

```sh
htz-scripts init ../new-component-module
```

**Comment by TxHawks** [comment]
That's very similar to what I had in mind, I'd just like to encapsulate it in a script in the root `package.json` so that developers can simply run `yarn run init [<package-name> <path>]` and have some files created and populated with correct content automatically for them.

We can either have the init script as script in the root dir, or list `htz-react-base` as a `devDependency` of the root `package.json`

**Comment by exogen** [comment]
Great point, I forgot about scripts in the root, let's put it there.
