### ISSUE TITLE
"Zapp" list (4 articles in main block)

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#1201]
## Issue Type

**New Feature**

## Description
* titles
* comments count
* author
* rank
* reporting from
* publish / update date (same logics as in article page)
* image / media

For mobile (break S):
* Ignore image of the 4th item
* show clicktracker element - com.polobase.ClickTrackerBannerElement

*** BI ACTIONS ***
Action code – 109

Additional info:
{
	"isReact":true,
	"ArticleId":"",
	"ListId":"",
	"Platform":"[web/mobile]",
	"NoInList":6,
	"ViewName":""
}

## Links

**Designs:**
* XL WIDE - https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5bf282493901503f0b5b2fb4
* XL - https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d0a4af2fc23b8519e06
* L - https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d09b581321f028ef18a
* M - https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d09592c20200b311ee4
* S - https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d08b233e423a69b69cb

## High Level Design
**Participants:**
  1. [ Insert name ]

**Overview:**
  * [ Insert description ]

## Testing Requirements

  * [ Insert description ]

## Work Time Estimation

[n] hours

**Comment by oren-l** [comment]
https://github.com/Haaretz/htz-frontend/pull/1273 is merged
