### ISSUE TITLE
Fix facebook pixel problems

### ISSUE THREAD

**Issue by innbal** [Haaretz/htz-frontend#1207]
עמוד רכישה עברית, גם הארץ וגם דה מרקר:
להוריד פיקסל שנקרא
lead.

רק בדה מרקר:
הפיקסל של בחירת המוצר
add to cart
מופעל פעמיים.
יכול להיות שזה בגלל שמשתמשים שונים עוברים תהליכים שונים.
צריך לוודא שיוצא רק פעם אחת עבור כל משתמש.

רק בהארץ:
בבחירת מוצר בעמוד
price
לא מופעל הפיקסל
add to cart
בבחירה במוצר החודשי
אבל מופעל פעמיים במוצר השנתי.

**Comment by kedarguy** [comment]
#1229
