### ISSUE TITLE
"Vogel" view

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#1250]
## Issue Type

**New Feature**

## Description
* Image - only in the first item and not in mobile
* teaser title & exclusive title
* list title

*** BI ACTIONS ***
Action code – 109

Additional info:
{
"isReact":true,
"ArticleId":"",
"ListId":"",
"Platform":"[web/mobile]",
"NoInList":6,
"ViewName":""
} 

## Links
**Designs:**
* XL: https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d3cf2674023e84900f3
* L: https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d3bf2674023e8490088
* M: https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5be19d3cd1db0a1fdf9213e6
* S: https://app.zeplin.io/project/5bfbc455d0bcdb4d8fbdf61b/screen/5c07ba71ee784db7824f15ea

## High Level Design
**Participants:**
  1. [ Insert name ]

**Overview:**
  * [ Insert description ]

## Testing Requirements

  * [ Insert description ]

## Work Time Estimation

[n] hours

**Comment by oren-l** [comment]
https://github.com/Haaretz/htz-frontend/pull/1283 is merged
