### ISSUE TITLE
Make update-scripts command organize added scripts better

### ISSUE THREAD

**Issue by exogen** [Haaretz/htz-frontend#14]
Minor complaint: on my first real-world use of `update-scripts` on the `htz-components` package, I realized that the current solution just adds any new scripts to the end of `scripts`. Even though the order doesn't matter, personally I prefer them to be alphabetized so I can find them more easily – or at the very least grouped thematically. We could do this before serializing back into the updated `package.json`.

**Comment by TxHawks** [comment]
+ 1 for alphabetized
