### ISSUE TITLE
Fix flexbox in "vogel" & "gamal" lists

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#1608]
![gamalbug](https://user-images.githubusercontent.com/30293685/52342684-baa0da00-2a1e-11e9-9150-cec754531ce9.png)
![vogelbug](https://user-images.githubusercontent.com/30293685/52342688-bd033400-2a1e-11e9-8d2c-93736496fa6c.png)

**Comment by TawKhoury** [comment]
Done
