### ISSUE TITLE
CMS data endpoint and rendering

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#17]
Set up a page endpoint that can render a React page based on existing CMS. Analyze JSON output format and tweak as necessary.

@eliagrady, @tomerbanin - We need to share any query parameters going in and the shape of the output data with @exogen so that he can continue working as planned.

**Comment by eliagrady** [comment]
@tomerbanin , I have a local branch called 'testing-react' with semi-running endpoints (currently for pages and article pages), how do you suggest we expose it? run it on pdev?

**Comment by TxHawks** [comment]
Isn't pdev is only available in our local network?

**Comment by eliagrady** [comment]
JSON samples (not final)
Homepage: https://pastebin.com/a5G5CB4L
Premium Standard Article Page: https://pastebin.com/EH9a1W1i

**Comment by TxHawks** [comment]
Endpoints are `contentId`s or predefined routes, e.g., section pages, that are translated to `contentId`s by the CMS's dispatcher.

The server gets the user's credentials from the request header (through a cookie), and decides what data to return accordingly. A `block=true` param will be added to the response header by the CDN.

A user's state may change mid-session in the following scenarios:
  * The user logged in
  * The user logged out
  * The user completed the registration process
  * The user completed the subscription process

The type of user determines the JSON output, and users receiving a closed page will be served a much leaner JSON.

We should examine at some point which fields should be served exploded and which imploded (i.e., containing only minimal data.

**Comment by exogen** [comment]
Info I'll need to interface with this endpoint:

* Public production URL
* Development/staging URLs, if applicable – with any necessary credentials if those environments are private

Will add more if I think of them.

**Comment by eliagrady** [comment]
Currently, there's no public production URL.
I've mocked sample JSON responses to the homepage, and to a premium article page.
[https://alerts.haaretz.co.il/papi/home.json](https://alerts.haaretz.co.il/papi/home.json)
[https://alerts.haaretz.co.il/papi/article.json](https://alerts.haaretz.co.il/papi/article.json)

**Comment by exogen** [comment]
What would really help me working with this data is if there were a visual mapping from these JSON fields to the home and article pages. Currently I'm just guessing and rendering placeholders anyway, but it would help a lot.

**Comment by exogen** [comment]
btw, I think these files are malformed. They're JS, not JSON because the keys aren't quoted, but that's fine. The real problem is that quotes in values don't appear to be escaped, so I can't load them as-is.

**Comment by eliagrady** [comment]
[https://jsonlint.com/?json=https://alerts.haaretz.co.il/papi/home.json](https://jsonlint.com/?json=https://alerts.haaretz.co.il/papi/home.json)
[https://jsonlint.com/?json=https://alerts.haaretz.co.il/papi/article.json](https://jsonlint.com/?json=https://alerts.haaretz.co.il/papi/article.json)

Output derived from new Gson().toJson() call, so it should be valid - it passes JSONlint.
Can you please be more specific regarding to what seems to be the problem? (i.e: a line number?)

**Comment by exogen** [comment]
@eliagrady Sorry, I was referring to the files on pastebin as invalid since the endpoint hasn't worked for me until now, it wasn't loading at all.

**Comment by TxHawks** [comment]
Notes from conversation with @exogen: 
* Each content element should specify it's `view`, either in form of a string, or as an id of some sort that we can map. From a quick examination of the json, `contentType` often doesn't mean much.
* group elements do not give us any useful data, we can't know what to render based on that. See `בארץ ובעולם` in the `topWideSecondary` array in `home.json`

**Comment by exogen** [comment]
Some remaining TODOs:

* `Access-Control-Allow-Origin` was duplicated in the headers for a bit, but now it's missing again.
* What are the input query parameters to these endpoints? Just `contentId`? Page type and content ID? Full user-facing URL? Will the client already know the `contentId` of any page data it needs to fetch ahead of time? (e.g. the `contentId` of the home page, since it's not in the URL – will it be hardcoded in the app? Or just never need to be used?)

**Comment by exogen** [comment]
Relevant comments for future reference:

* https://github.com/Haaretz/htz-frontend/pull/39#issuecomment-327733017
* https://github.com/Haaretz/htz-frontend/pull/39#issuecomment-327742509

**Comment by eliagrady** [comment]
I think Access-Control-Allow-Origin is being added on a CDN cache - this is why it was duplicated when we've added it to the headers on the nodejs server, and this is also why it was removed when we removed it.
