### ISSUE TITLE
blogs article's comments number in opinions list

### ISSUE THREAD

**Issue by pelegash** [Haaretz/htz-frontend#1713]
## Issue Type
**Bug fix**

## Description
Please display blogs article's comments number in opinions list

https://www.haaretz.co.il/blogs/kobiniv/BLOG-1.6982411

![image](https://user-images.githubusercontent.com/48085141/53694834-ba48f400-3dbc-11e9-8e79-866c4624d348.png)

**Comment by TawKhoury** [comment]
Blog article teaser data missing comments count field.
@avipk Knows about it, it will be fixed in papi.

**Comment by pelegash** [comment]
Thanks

**Comment by avipk** [comment]
I added the comment-count for blogs.
a Hotfix is ready for deployment.
