### ISSUE TITLE
Image should crop image to aspect based on full, even if not defined by editer

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#196]
## Issue Type

**Bug fix**

## Description
Say there are no defined crops in the CMS for image `x.jpg`, and it is called in a
`<Quote />` with an image. Images in quotes are square, and the image component
should be able to either use the crop defined by the editors for this aspect ratio, or
when one does not exist, automatically crop the image correctly based on `full` and
gravitate to the center.

e.g., when `square` does not exist in the cms, do this
```
+-------------+         +--+-------+--+
|             |         |  :       :  |
|             |    =>   |  :       :  |
|             |         |  :       :  |
+-------------+         +--+-------+--+
```

**Comment by EranM6** [comment]
Still not working for Infographic (`<Picture />`)
