### ISSUE TITLE
Actions and Query String Params for Mad Pop-up

### ISSUE THREAD

**Issue by innbal** [Haaretz/htz-frontend#2300]
### fields for BI Actions:

field|value
-- | --
Action When Viewed|155
Action When Pressed|3
feature_type|Marketing
feature|Subcription End Pop-up
campaign_name|polopoly name (e.g. 2 Weeks - Regular)
campaign_details|Hourglass

**Comment by innbal** [comment]
### fields href query string:

field|value
-- | --
source|Pop_up
medium|site
campigan|polopoly name (e.g. 2   Weeks - Regular)
content|Hourglass

**Comment by TawKhoury** [comment]
WIP
branch: `feature/mad-popup-logic`
***bi actions needs to be checked with real data.***

**Comment by innbal** [comment]
There was a mix up with the href parameters. Should be
