### ISSUE TITLE
בכל העמודים הפונט מוצג כאריאל במקום open sans

### ISSUE THREAD

**Issue by innbal** [Haaretz/htz-frontend#248]
בכל העמודים הפונט מוצג כאריאל במקום open sans
בהרבה מקרים גודל הפונט לא תואם לעיצוב

**Comment by kedarguy** [comment]
@TxHawks regarding the fonts, did you decide how to take care of them in production yet? or should I look for a quick fix?

@innbal after taking care of logic and urgent bug, will do a refactor for all components UI and make sure fonts are correct
