### ISSUE TITLE
עמוד נחיתה ראשון

### ISSUE THREAD

**Issue by innbal** [Haaretz/htz-frontend#249]
צריך לעדכן את העיצוב עם תמונות חדשות:
https://app.zeplin.io/project/5a7ad60bde7607ac762fa99d/screen/5a8426da8edcef3fa4a7ebf5

העמודות של הטקסטים בחלק התחתון אינן שוות ברוחבן

 הכפתור הכתום- לכל מסלולי המנויים לא מקליק

**Comment by kedarguy** [comment]
currently removed from flow
