### ISSUE TITLE
לשנות טקסט בהרשמה/התחברות

### ISSUE THREAD

**Issue by innbal** [Haaretz/htz-frontend#272]
בעמוד רכישה צריך לתקן את הטקסט של ההרשמה/התחברות ליד הצ'ק בוקס.
לטקסט הבא:

אני מאשר/ת קבלת דיוורים, המלצות קריאה והצעות לרכישת מינוי מאתרי הארץ-TheMarker

**Comment by EranM6** [comment]
השארתי את תנאי השימוש, אז כרגע השורה היא:
אני מאשר/ת את תנאי השימוש, וכן קבלת דיוורים, המלצות קריאה והצעות לרכישת מינוי מאתרי הארץ-TheMarker

**Comment by innbal** [comment]
Updated in #311
