### ISSUE TITLE
TM article page - mobile chart bug

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#2727]
## Issue Type

**Bug fix**

## Description
Fix TM chart's tabs in mobile: 
https://www.themarker.com/markets/.premium-1.8430300?v=69DB87FE822766490CE06863071504C9

![TM_mobile_chart](https://user-images.githubusercontent.com/30293685/72962411-ee564a80-3dbc-11ea-8310-1da5be821ac6.png)

**Comment by chenaviv** [comment]
Is there a working example of this issue?
Also, I couldn't find a mobile design for this graph. Is there one?
