### ISSUE TITLE
להוריד פסיק מהטקסטים אחרי שהיוזר בוחר מסלול

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#314]
בכל השלבים צריך להוריד פסיק בטקסט אחרי המילה "בחרתם":

**Comment by RotemKa** [comment]
![default](https://user-images.githubusercontent.com/38319928/39128663-0bbd12e2-4711-11e8-9ca7-752b89cd486b.png)

**Comment by innbal** [comment]
All text ammendmets will be gathered into one issue
