### ISSUE TITLE
חסרה קוביית הרשמה לניוזלטר בדף תודה שרכשת

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#317]
חסרה קוביית הרשמה לניוזלטר בדף תודה שרכשת

**Comment by RotemKa** [comment]
![default](https://user-images.githubusercontent.com/38319928/39129783-057cdee6-4714-11e8-98b1-9e4546e18397.png)

**Comment by kedarguy** [comment]
מחכים לסיום קומפוננטת ניוזלטר של טאופיק

**Comment by innbal** [comment]
moved to #300
