### ISSUE TITLE
חזור לעמוד תודה שרכשת מגיעה לעמוד 500

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#318]
כאשר רוכשים ולוחצים על הפניה לדף הבית ולוחצים על חזור בדפדפן לעמוד הרכישה מגיעים לעמוד 500

**Comment by RotemKa** [comment]
![500](https://user-images.githubusercontent.com/38319928/39129930-7e069e2e-4714-11e8-8399-7b7365ae7397.png)

**Comment by kedarguy** [comment]
should be fixed after closing issue #281
