### ISSUE TITLE
מנוי משולב לא מזוהה בעמוד רכישה של דה מרקר

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#319]
1. ביצעתי רכישה למוצר משולב ונכנסתי לעמוד רכישה של דה מרקר עם מנוי משולב, מוצגות הצעות של דה מרקר ומשולב- לא תקין
2. עשיתי לוגין עם מנוי משולב משלם ונכנסתי לעמוד רכישה הארץ ודה מרקר והגעתי לעמוד 500, כי חסרה שם הודעה

**Comment by RotemKa** [comment]
![default](https://user-images.githubusercontent.com/38319928/39133314-93dd9286-471c-11e8-94a9-ea415a7c8e9f.png)

**Comment by kedarguy** [comment]
ערן מטפל עכשיו בדף תודה וזה אמור להסתדר
