### ISSUE TITLE
לעדכן הפניות בעמוד רכישה דה מרקר

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#321]
לעדכן הפניות בעמוד רכישה דה מרקר
פוטר-
דף הבית- http://www.themarker.com/
שאלות ותשובות- https://www.themarker.com/misc/faq
צור קשר- https://www.themarker.com/misc/contact-us
לעדכן לוגו של דה מרקר

**Comment by kedarguy** [comment]
homepage link fixed in pull request #391
