### ISSUE TITLE
אין קפיצה לשלב של ההצעות מהאינדקס

### ISSUE THREAD

**Issue by RotemKa** [Haaretz/htz-frontend#323]
כאשר אני נכנסת לעמוד רכישה של הארץ או דה מרקר עם מנוי משלם של הארץ או דה מרקר, אני אמורה לקפוץ לשלב 3 של ההצעה של מנוי משולב.
מה שקורה בפועל אני מגיעה לעמוד נחיתה הראשון- לא תקין

**Comment by kedarguy** [comment]
השאלה אם צריך להקפיץ, רוב היוזרים לא מגיעים לדף נחיתה ואז מוקפצים, וברגע שיוזר ימשיך לשלב הראשון הוא יוקפץ.
@innbal ?

**Comment by innbal** [comment]
נכון שהעברנו את ההקפצה מעמוד הפתיחה לעמוד הטבלה - אבל גם משם המשתמש לא מוקפץ למקום הנכון...
אני פותחת את המשימה של "התחלה במקום הנכון"
