### ISSUE TITLE
App build broken by move to Yarn Workspaces

### ISSUE THREAD

**Issue by TxHawks** [Haaretz/htz-frontend#53]
@exogen in Slack:
> `build` in the app is broken and spits out a ton of errors (it’s just running a vanilla `next build`, we don’t do anything fancy), I assume because Next can’t resolve things properly when they’re hoisted (edited)

**Comment by TxHawks** [comment]
I can't seem to reproduce this. Build works for me after doing `yarn run bootstrap` from the root dir:

<img width="859" alt="screen shot 2017-09-10 at 13 48 41" src="https://user-images.githubusercontent.com/5658514/30248600-5d4a173e-9633-11e7-9255-24888c72c631.png">

@exogen, can you try checking out `fix/yarn-workspaces-with-lerna`, run 
```sh
yarn run bootstrap && cd packages/apps/haaretz.co.il && yarn run build
```

And see if this still happens for you?

**Comment by exogen** [comment]
It does work! I get the same error as before only when `htz-components` hasn't been built first, which makes sense, so I think that was the problem.

(It would be cool if running `build` in a package automatically built any symlinked dependencies as well, as in a real npm-registry-installed scenario they'd always already be built. But that's just a nice-to-have.)

**Comment by exogen** [comment]
Relevant to needing to run `build` ourselves instead of letting lifecycle scripts handle it: https://github.com/yarnpkg/yarn/issues/3911
