### ISSUE TITLE
SEO tags missing

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#635]
## Issue Type

**Bug fix**

## Description
Take a look at this article for exampls -> https://www.haaretz.co.il/news/politi/1.6289040
The problems are:

* No AMP. should be: 
link rel="amphtml" href="https://www.haaretz.co.il/amp/news/world/america/1.6291089"/> 

* Title tag is missing. Should be:
 <title>הוועדה לקידום חוק הלאום אישרה אותו לקריאה שנייה ושלישית במליאה - פוליטי - הארץ</title>        
                              
* Canonical tag is missing. Should be:
<link rel="canonical" href="https://www.haaretz.co.il/news/politi/1.6289040"/>

**Comment by tamirbenCA** [comment]
pull request #649
