### ISSUE TITLE
Breadcrumbs URL bug

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#638]
## Issue Type

**Bug fix**

## Description
Breadcrumbs click causes a fault in the URL, (the number is useless) e.g: 
https://www.haaretz.co.il/news/politi/2.696
https://www.haaretz.co.il/news/2.409

**Comment by kedarguy** [comment]
The problem is the base domain is react-prod, once it will be in production it will work, after getting the 404 if you switch the react-prod to www it works
