### ISSUE TITLE
Opt In

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#667]
## Issue Type

**New Feature**

## Description
Opt-in to new article page from old page.
* Create HTML elements for Opt-in ruler to embed in Polopoly
* Elements will be shown under these conditions:
       1. The page is an article page, regular type only
       2. Opt out field in Mongo DB is "false".
       3. The user is a p-user (subscriber)
* When clicking the opt-in button, set "react=true" cookie, update Mongo DB and refresh the page

**Designs:**
* Desktop: https://app.zeplin.io/project/59b4e63a7a92547269089328/screen/5aa7cdd422a966750fe0849d
* Mobile: https://app.zeplin.io/project/59b4e63a7a92547269089328/screen/5b5db2c96bc2e3393f941f7f

**Comment by avipk** [comment]
Done for desktop ONLY. as @adibi83 requested.
Merged to master
