### ISSUE TITLE
DFP Parameters

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#682]
## Issue Type

**New Feature**

## Description
Key = pageType
value = react

**Comment by oren-l** [comment]
The requirement is to add the following fields to the dfp:
* htz_user_type
* tm_user_type
* hdc_user_type
* section
* subsection

**Comment by oren-l** [comment]
Additional requirement to add the following fields:
* pageType (value in our project is always "react")
* tags (tagsList.contentName in the papi)
* anonymousIdKey (window.UserUtil.getLoginInfo().anonymousId)
* 'group${groupKey}_sso' (value is the innerGroupIndex)
