### ISSUE TITLE
Mobile - embed bug

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#938]
## Issue Type

**Bug fix**

## Description
Embeds cut bug in mobile -> https://www.haaretz.co.il/1.6515706
Happens in iPhone 5/SE

**Comment by oren-l** [comment]
no real issue here, in chrome dev tools it seems like there is a problem but testing on BrowserStack did not reproduce the issue.

**Comment by adibi83** [comment]
Another example in prod: https://www.haaretz.co.il/news/politi/1.6529349
