### ISSUE TITLE
Article Body - Images

### ISSUE THREAD

**Issue by adibi83** [Haaretz/htz-frontend#95]
## Issue Type

* [ ] Bug fix
* [X] New Feature
* [ ] Update to existing feature
* [ ] General discussion

## Related Issues
[#0]

## Description

* [ ] legacy - aspects
* [ ] legacy - animated GIF
* [ ] open image in full screen - upper-left zoom button to enlarge image. In full screen mode show image text & credit on right, and accessibility in mouse hover; exit full screen using  "X" button on left or ESC button.
* [ ] Polopoly image fields - image text, accessibility (mouse hover), credit

### Configuration options

* [ ] legacy - "place after paragraph"

### Measurement Requirements
  
  * [ ] ds - [ Insert requirements ]
  * [ ] tag manager - [ Insert requirement ]
  
### A11Y Concerns

**Focus management:**
  * [ Insert requirement ]

**Assistive tech (scrren readers):**
  * [ Insert requirement ]

**Color contrast:**
  * [ Insert requirement ]

## Links

**Designs:**
  Desktop: https://app.zeplin.io/project/59b4e63a7a92547269089328/screen/59b4e670b310f781615188dd 

## High Level Design
**Participants:**
  1. [ Insert name ]

**Overview:**
  * [ Insert description ]

## Testing Requirements

  * [ Insert description ]

## Work Time Estimation

[n] hours

**Comment by EranM6** [comment]
@adibi83 @TxHawks
A small clarification please;
The share icons (mail, whatsapp & Facebook) should share the image or the article's URL ??

**Comment by adibi83** [comment]
Image URL
